### ISSUE TITLE
Latency and scaling question

### ISSUE THREAD

**Issue by lonnietc** [cunicu/cunicu#313]
Hello,

I am working on the some research for a new p2p project and I was wondering some questions about cunicu that I hope you will try to answer for me.

1. What is the latency for packets relative to native no active vpn?
2. How well does cunicu scale.
3. Do cunicu node act as relay mesh nodes to pass traffic to other nodes?

Any information that you might be able to provide would be greatly appreciated.
Thanks and have a great day

**Comment by stv0g** [comment]
Hi @lonnietc,

Sure :) I should mentioned that cunicu is still in an alpha state, but here are my answers:

1. Latency will be almost the same, as cunicu will establish direct p2p connections between all peers. However, there is some small overhead due to the Kernel WireGuard VPN. But this only becomes really noticeable in local networks with really high pkts/s numbers. In some situation the network conditions do not allow for direct p2p connections in which we currently can optionally fall back to TURN relays. This will result in higher latencies depending on where the TURN relay is located.
2. That’s difficult to answer. I have done some simple scaling tests with Gont, where I was able to establish p2p between 50 cunicu agents on a single machine using an emulated network (network namespaces). Cunicu currently attempts to build p2p to each peer available. This is optimal for latency, but bad for scalability. So in some sense your 1st and 2nd questions are two goals which are difficult to accomplish at once. I am planning to make cunicu a bit smarter later on by observing which p2p connections are actually used using some traffic inspection. In such cases the p2p mesh can be lazily constructed which highly benefits scalability. I would also love to combine this with a mesh routing protocol like Babel to reroute packets over intermediate nodes as long as no direct p2p connection is available. The combination of lazy connection establishment with a dynamic mesh routing protocol should be pretty powerful.
3. Currently not. I am planning to implement this by integrating a Babel speaker into cunicu. Babel is a small distance vector routing protocol build for overlay and wireless mesh networks. I am currently working on a Go implementation here: http://github.com/cunicu/go-babel

**Comment by stv0g** [comment]
Please let me know if you have more questions :) I will close the ticket here for now. But please feel free to reopen it. We are always looking for contributors!
